GET http://localhost:8080/api/premises/buildings
###
GET http://localhost:8080/api/premises/buildings?addresslike=Ставрополь
###
GET http://localhost:8080/api/premises?isAvailable=false
###
POST http://localhost:8080/api/premises
content-type: application/json

{
	"address": "Ставрополь, ул. Пушкина, 1",
	"landlordId": 1,
    "floor": 3,
    "number": "303",
    "area": 16.0,
    "description": "Помещение с видом на лес",
    "advertisedPrice": 10000
}
###
GET http://localhost:8080/api/premises?isAvailable=true
###
GET http://localhost:8080/api/premises?isAvailable=true&totalpricemax=11000
###
GET http://localhost:8080/api/premises/2
###
